# This POD mounts the nfs volume claim into /var/www/html and
# serves PHP web page.

apiVersion: v1
kind: ReplicationController
metadata:
  name: web-frontend
spec:
  replicas: 2
  selector:
    role: web-frontend
  template:
    metadata:
      labels:
        role: web-frontend
    spec:
      containers:
      - name: web-frontend
        image: php:5.5-apache
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
            - name: nfs
              mountPath: "/var/www/html"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: web-storage-claim
          readOnly: true
